pipeline:
  tags: {}
  template:
    templateRef: cdflexi13pip
    versionLabel: v1
    templateInputs:
      stages:
        - parallel:
            - insert:
                identifier: insert1
                stages:
                  - stage:
                      name: Helm
                      identifier: Helm
                      description: ""
                      type: Deployment
                      spec:
                        deploymentType: NativeHelm
                        services:
                          values:
                            - serviceRef: helmSrv
                              serviceInputs:
                                serviceDefinition:
                                  type: NativeHelm
                                  spec:
                                    artifacts:
                                      primary:
                                        primaryArtifactRef: <+input>
                                        sources: <+input>
                            - serviceRef: helmSrv2
                          metadata:
                            parallel: true
                        environmentGroup:
                          envGroupRef: envGrp
                          metadata:
                            parallel: true
                          deployToAll: true
                          environments: <+input>
                        execution:
                          steps:
                            - step:
                                name: Helm Deployment
                                identifier: helmDeployment
                                type: HelmDeploy
                                timeout: 10m
                                spec:
                                  skipDryRun: false
                          rollbackSteps:
                            - step:
                                name: Helm Rollback
                                identifier: helmRollback
                                type: HelmRollback
                                timeout: 10m
                                spec: {}
                      tags: {}
                      failureStrategies:
                        - onFailure:
                            errors:
                              - AllErrors
                            action:
                              type: StageRollback
            - insert:
                identifier: insert3
                stages: <+input>
            - insert:
                identifier: insert4
                stages: <+input>
        - insert:
            identifier: insert2
            stages: <+input>
        - insert:
            identifier: insert5
            stages: <+input>
  projectIdentifier: chetanTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  identifier: cdflexi13pipeline_Clone
  name: cd-flexi-13-pipeline - Clone
