pipeline:
  name: cd-flexi-13-pipeline
  identifier: cdflexi13pipeline
  tags: {}
  template:
    templateRef: cdflexi13pip
    versionLabel: v1
    templateInputs:
      stages:
        - parallel:
            - insert:
                identifier: insert1
                stages: <+input>
            - insert:
                identifier: insert3
                stages: <+input>
            - insert:
                identifier: insert4
                stages: <+input>
        - insert:
            identifier: insert2
            stages: <+input>
        - insert:
            identifier: insert5
            stages: <+input>
  projectIdentifier: chetanTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
