pipeline:
  name: fdsfds
  identifier: fdsfds
  projectIdentifier: import_UI_automation
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: wq
        identifier: wq
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: wqe
                  identifier: wqe
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
