pipeline:
  name: opi
  identifier: opi
  projectIdentifier: imranTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: qqwwe
        identifier: qqwwe
        description: adsdasd
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: eqqw
                  identifier: eqqw
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
