pipeline:
  name: testChild123
  identifier: testChild123
  projectIdentifier: TestAmit123
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 'hi123'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
