pipeline:
  name: demo23
  identifier: demo23
  projectIdentifier: imr
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: q22
        identifier: q22
        description: cnkjchbsopppppppp
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: e3
                  identifier: e3
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
