pipeline:
  name: Deploy any service on Dev1
  identifier: Deploy_any_service_on_Dev1
  projectIdentifier: check26Sense
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: config
        identifier: config
        template:
          templateRef: org.Rolling_dev_deploy_any
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceRef: <+input>
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    variables:
                      - name: desired_replicas
                        type: Number
                        value: <+input>
                      - name: max_replicas
                        type: Number
                        value: <+input>
                    manifests:
                      - manifest:
                          identifier: k8smanifests
                          type: K8sManifest
                          spec:
                            store:
                              type: Github
                              spec:
                                branch: <+input>
                    artifacts:
                      primary:
                        type: Ecr
                        spec:
                          imagePath: <+input>
                          tag: <+input>
              infrastructure:
                environmentRef: <+input>
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    namespace: <+input>
